In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
#Keras is a high-level neural networks API, written in Python and capable of running on top of TensorFlow
#It was developed with a focus on enabling fast experimentation. Being able to go from idea to result with the least possible delay is key to doing good research.
#Supports both convolutional networks(Image processing) and recurrent networks(Natural language processing), as well as combinations of the two.



from keras.preprocessing.text import Tokenizer#Used to split data
from keras.preprocessing.sequence import pad_sequences#used to pad data
from keras.models import Sequential#The Sequential model is a linear stack of layers
from keras.layers import Dense, Embedding, LSTM
#A dense layer is just a regular layer of neurons in a neural network. Each neuron recieves input from all the neurons in the previous layer, thus densely connected
#Dropout is a regularization technique, which aims to reduce the complexity of the model with the goal to prevent overfitting.
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
import re

Using TensorFlow backend.


In [2]:
#reading data from file
data = pd.read_csv('Sentiment.csv')

# Keeping only the neccessary columns
data = data[['text','sentiment']]
print(len(data))#number of training data

13871


In [3]:
data = data[data.sentiment != "Neutral"]#remove neutral data sets because it gives no information

In [4]:
print (data)



                                                    text sentiment
1      RT @ScottWalker: Didn't catch the full #GOPdeb...  Positive
3      RT @RobGeorge: That Carly Fiorina is trending ...  Positive
4      RT @DanScavino: #GOPDebate w/ @realDonaldTrump...  Positive
5      RT @GregAbbott_TX: @TedCruz: "On my first day ...  Positive
6      RT @warriorwoman91: I liked her and was happy ...  Negative
8      Deer in the headlights RT @lizzwinstead: Ben C...  Negative
9      RT @NancyOsborne180: Last night's debate prove...  Negative
10     @JGreenDC @realDonaldTrump In all fairness #Bi...  Negative
11     RT @WayneDupreeShow: Just woke up to tweet thi...  Positive
12     Me reading my family's comments about how grea...  Negative
14     RT @pattonoswalt: I loved Scott Walker as Mark...  Positive
15     Hey @ChrisChristie exploiting the tragedy of 9...  Negative
16     RT @CarolCNN: #DonaldTrump under fire for comm...  Negative
17     RT @johncardillo: Guess who had most speaking ...  Nega

In [5]:
data['text'] = data['text'].apply(lambda x: x.lower())#change it all to lowercase to avoid any differences

print(data)



                                                    text sentiment
1      rt @scottwalker: didn't catch the full #gopdeb...  Positive
3      rt @robgeorge: that carly fiorina is trending ...  Positive
4      rt @danscavino: #gopdebate w/ @realdonaldtrump...  Positive
5      rt @gregabbott_tx: @tedcruz: "on my first day ...  Positive
6      rt @warriorwoman91: i liked her and was happy ...  Negative
8      deer in the headlights rt @lizzwinstead: ben c...  Negative
9      rt @nancyosborne180: last night's debate prove...  Negative
10     @jgreendc @realdonaldtrump in all fairness #bi...  Negative
11     rt @waynedupreeshow: just woke up to tweet thi...  Positive
12     me reading my family's comments about how grea...  Negative
14     rt @pattonoswalt: i loved scott walker as mark...  Positive
15     hey @chrischristie exploiting the tragedy of 9...  Negative
16     rt @carolcnn: #donaldtrump under fire for comm...  Negative
17     rt @johncardillo: guess who had most speaking ...  Nega

In [6]:
data['text'] = data['text'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))#remove unnecessary expressions like @
print (data)

                                                    text sentiment
1      rt scottwalker didnt catch the full gopdebate ...  Positive
3      rt robgeorge that carly fiorina is trending  h...  Positive
4      rt danscavino gopdebate w realdonaldtrump deli...  Positive
5      rt gregabbott_tx tedcruz on my first day i wil...  Positive
6      rt warriorwoman91 i liked her and was happy wh...  Negative
8      deer in the headlights rt lizzwinstead ben car...  Negative
9      rt nancyosborne180 last nights debate proved i...  Negative
10     jgreendc realdonaldtrump in all fairness billc...  Negative
11     rt waynedupreeshow just woke up to tweet this ...  Positive
12     me reading my familys comments about how great...  Negative
14     rt pattonoswalt i loved scott walker as mark h...  Positive
15     hey chrischristie exploiting the tragedy of 91...  Negative
16     rt carolcnn donaldtrump under fire for comment...  Negative
17     rt johncardillo guess who had most speaking ti...  Nega

In [7]:
for idx,row in data.iterrows():
    row[0] = row[0].replace('rt',' ')
print (data)

                                                    text sentiment
1        scottwalker didnt catch the full gopdebate l...  Positive
3        robgeorge that carly fiorina is trending  ho...  Positive
4        danscavino gopdebate w realdonaldtrump deliv...  Positive
5        gregabbott_tx tedcruz on my first day i will...  Positive
6        warriorwoman91 i liked her and was happy whe...  Negative
8      deer in the headlights   lizzwinstead ben cars...  Negative
9        nancyosborne180 last nights debate proved it...  Negative
10     jgreendc realdonaldtrump in all fairness billc...  Negative
11       waynedupreeshow just woke up to tweet this o...  Positive
12     me reading my familys comments about how great...  Negative
14       pattonoswalt i loved scott walker as mark ha...  Positive
15     hey chrischristie exploiting the tragedy of 91...  Negative
16       carolcnn donaldtrump under fire for comments...  Negative
17       johncardillo guess who had most speaking tim...  Nega

In [8]:
batch_size = 5000
tokenizer = Tokenizer(nb_words=batch_size, split=' ')#split as words

tokenizer.fit_on_texts(data['text'].values)
X = tokenizer.texts_to_sequences(data['text'].values)
#convert the text into stream of numbers so it can be fed into the computer

c:\users\mahalakshumi\myenv\lib\site-packages\keras_preprocessing\text.py:177: UserWarning: The `nb_words` argument in `Tokenizer` has been renamed `num_words`.
  warnings.warn('The `nb_words` argument in `Tokenizer` '


In [9]:
for ll in X:
    print(len(ll), ll)

19 [363, 122, 2404, 1, 703, 2, 39, 58, 237, 37, 210, 6, 4277, 174, 1761, 12, 1324, 1409, 743]
19 [16, 284, 252, 5, 4278, 821, 102, 167, 26, 2796, 136, 6, 1, 173, 12, 2, 233, 724, 17]
16 [1261, 2, 303, 23, 1943, 1, 1632, 216, 12, 1, 704, 6, 185, 207, 371, 670]
20 [4279, 2405, 127, 17, 53, 263, 410, 9, 82, 3322, 304, 441, 1325, 1762, 1150, 62, 1944, 194, 2, 51]
22 [2797, 9, 1151, 167, 8, 21, 1326, 63, 9, 614, 188, 21, 189, 4, 34, 1, 563, 19, 822, 2, 44, 744]
19 [12, 1, 2137, 168, 96, 547, 34, 1, 103, 589, 2138, 52, 59, 1763, 7, 4280, 17, 615, 2]
10 [2798, 39, 149, 26, 823, 13, 2, 926, 2406, 2799]
6 [23, 12, 46, 3323, 2800, 16]
16 [2139, 36, 1945, 47, 4, 860, 20, 69, 2, 174, 548, 6, 1, 58, 275, 335]
11 [31, 1208, 53, 4281, 453, 22, 54, 146, 1, 2, 21]
14 [671, 9, 528, 305, 169, 55, 2407, 12, 2140, 1327, 182, 13, 47, 2]
14 [306, 372, 1, 4282, 6, 893, 14, 92, 466, 270, 2141, 5, 271, 2]
14 [2801, 266, 467, 966, 14, 453, 22, 107, 3324, 3325, 12, 17, 2, 475]
15 [3326, 616, 52, 186, 132, 175, 10

12 [430, 196, 487, 38, 7, 1451, 358, 4686, 220, 7, 77, 2]
20 [2947, 736, 548, 22, 1634, 213, 1, 1233, 6, 1, 608, 45, 42, 24, 525, 1, 1382, 6, 2, 928]
10 [4687, 1457, 1588, 27, 1, 238, 51, 2, 39, 58]
17 [39, 149, 2, 823, 539, 30, 882, 846, 22, 1, 295, 4688, 108, 117, 1, 42, 5]
17 [15, 59, 60, 1840, 60, 1383, 8, 60, 2548, 8, 220, 695, 6, 13, 1339, 2, 15]
16 [2948, 525, 582, 54, 990, 2475, 254, 3524, 1, 990, 62, 2949, 1118, 246, 376, 171]
10 [2950, 9, 38, 1, 936, 6, 16, 134, 1237, 2]
19 [2, 1, 948, 21, 12, 27, 1, 243, 104, 22, 4689, 187, 94, 28, 253, 2549, 1971, 213, 23]
21 [301, 943, 129, 39, 58, 29, 1, 2, 549, 458, 46, 635, 695, 4, 28, 11, 55, 7, 77, 126, 663]
7 [1558, 4690, 15, 107, 8, 1, 2]
12 [88, 5, 19, 175, 4, 11, 54, 22, 210, 211, 91, 2]
19 [296, 56, 105, 189, 4, 179, 20, 99, 131, 1785, 1190, 148, 4, 1298, 1136, 183, 14, 92, 104]
16 [671, 53, 88, 5, 2156, 4676, 134, 143, 4, 8, 75, 7, 502, 1299, 232, 2]
18 [1216, 53, 285, 1269, 6, 2550, 2, 137, 5, 180, 188, 80, 1474, 69, 1282, 46, 

13 [222, 218, 4, 65, 7, 1110, 954, 69, 6, 300, 1280, 2009, 2]
21 [1066, 1955, 4, 141, 204, 9, 111, 60, 468, 126, 72, 34, 1130, 1, 276, 141, 204, 1130, 15, 51, 2]
10 [1167, 1348, 2, 146, 25, 14, 197, 87, 275, 752]
18 [18, 25, 565, 34, 910, 1868, 27, 1049, 62, 61, 2274, 6, 87, 8, 15, 8, 96, 2]
20 [17, 1, 1381, 978, 6, 39, 149, 2, 46, 1, 453, 283, 4, 34, 930, 18, 25, 14, 930, 15]
15 [53, 3664, 131, 696, 75, 7, 2275, 69, 6, 295, 746, 1829, 22, 1090, 2]
11 [4900, 15, 347, 4, 1243, 2056, 38, 1, 295, 824, 2]
18 [40, 64, 2276, 22, 223, 14, 33, 138, 193, 166, 22, 505, 1472, 14, 7, 703, 1420, 2]
11 [4901, 96, 9, 43, 133, 1168, 9, 36, 133, 1222, 2]
12 [1414, 1415, 20, 21, 19, 29, 46, 939, 22, 29, 1, 2]
15 [10, 2609, 548, 18, 25, 507, 1, 26, 46, 1, 35, 28, 67, 1840, 2]
14 [3611, 443, 2156, 335, 59, 66, 6, 71, 592, 6, 2, 868, 4902, 714]
17 [1453, 38, 4903, 58, 1081, 6, 210, 416, 1109, 33, 352, 4904, 772, 9, 418, 33, 4350]
18 [1432, 2, 401, 266, 44, 4, 329, 26, 45, 7, 2277, 851, 104, 21, 1214, 24, 8

10 [1582, 59, 1, 123, 791, 43, 2940, 76, 2666, 2]
20 [358, 1779, 1, 607, 825, 29, 39, 149, 2, 2858, 253, 53, 1336, 5, 7, 759, 575, 24, 4, 53]
11 [1, 498, 1590, 5, 247, 981, 62, 3091, 3769, 1718, 2]
14 [1261, 23, 59, 1849, 293, 6, 2, 145, 121, 443, 44, 2024, 371, 265]
4 [3770, 23, 266, 2]
14 [99, 1023, 12, 8, 267, 60, 493, 6, 112, 1892, 79, 2, 401, 51]
21 [1, 174, 276, 4, 3592, 6, 7, 1784, 5, 4, 3771, 4, 13, 55, 1, 18, 25, 27, 211, 25, 2]
17 [120, 19, 1843, 4, 728, 1961, 578, 1708, 6, 3390, 767, 5, 60, 1277, 4, 325, 2]
22 [3053, 7, 1298, 246, 15, 121, 32, 59, 7, 3092, 1232, 199, 701, 549, 458, 3447, 24, 113, 1587, 4, 74, 521]
11 [853, 1500, 8, 3093, 107, 103, 53, 424, 3772, 45, 2271]
17 [68, 289, 81, 19, 1608, 4, 2619, 914, 7, 238, 1596, 4, 443, 44, 8, 2158, 2]
20 [1425, 1, 174, 108, 6, 1, 26, 121, 119, 46, 1, 3773, 160, 1115, 14, 1, 1700, 3094, 467, 1704]
19 [1, 103, 276, 1, 2, 287, 28, 253, 3095, 5, 56, 3096, 47, 8, 3774, 44, 137, 461, 1660]
8 [509, 3512, 197, 87, 5, 47, 45, 2]
15 [21

16 [93, 777, 34, 53, 288, 177, 14, 79, 32, 483, 210, 80, 499, 39, 58, 2]
11 [51, 296, 102, 1, 2, 13, 487, 16, 88, 59, 11]
13 [103, 7, 1244, 72, 566, 141, 204, 99, 17, 2327, 2, 154, 475]
22 [83, 116, 232, 387, 341, 32, 21, 2474, 55, 150, 3432, 292, 32, 21, 12, 6, 16, 833, 478, 17, 1719, 2]
23 [589, 46, 16, 166, 1024, 621, 24, 19, 308, 17, 48, 4, 65, 303, 3874, 973, 355, 900, 1, 486, 75, 2537, 2]
12 [7, 1094, 27, 39, 149, 2, 1580, 241, 110, 1891, 12, 1]
19 [1, 2, 39, 58, 21, 539, 9, 2632, 14, 8, 67, 1, 1446, 82, 34, 942, 14, 2927, 872]
20 [13, 565, 34, 1042, 1292, 45, 1, 2924, 4587, 4588, 29, 1, 2, 90, 368, 89, 4589, 19, 790, 700]
18 [15, 3123, 283, 1857, 921, 460, 9, 641, 83, 314, 3862, 411, 2326, 94, 75, 198, 13, 2]
9 [1162, 1494, 141, 204, 1109, 17, 420, 2569, 2]
11 [1, 628, 317, 1559, 150, 6, 40, 37, 132, 845, 2]
12 [3665, 3, 395, 4746, 623, 4747, 76, 46, 42, 507, 206, 3557]
20 [36, 7, 880, 282, 19, 627, 12, 1, 2, 429, 228, 431, 399, 610, 847, 505, 2471, 1560, 1362, 9]
14 [1427, 20, 

19 [638, 50, 57, 8, 42, 89, 67, 1102, 14, 431, 399, 101, 40, 65, 4, 329, 2261, 2, 265]
9 [636, 169, 1836, 176, 13, 1691, 123, 2, 333]
9 [367, 9, 43, 2725, 46, 6, 90, 35, 2]
15 [9, 676, 1, 2, 33, 68, 4944, 16, 15, 5, 2724, 2674, 12, 1, 353]
17 [3176, 9, 418, 1, 2, 8, 46, 9, 64, 144, 5, 863, 194, 21, 72, 258, 339]
19 [13, 21, 7, 12, 1, 3926, 522, 6, 332, 27, 1, 1366, 2218, 4, 1, 3848, 499, 4, 104]
5 [78, 15, 971, 7, 2]
11 [9, 36, 218, 180, 188, 1668, 39, 58, 2, 1485, 4771]
17 [3860, 35, 124, 4, 278, 219, 114, 2222, 2280, 63, 285, 7, 294, 6, 3001, 17, 137]
15 [2913, 2, 824, 690, 1737, 150, 455, 32, 661, 198, 33, 59, 307, 784, 265]
13 [1, 174, 108, 6, 1, 26, 39, 58, 1, 1078, 1909, 604, 2]
21 [463, 212, 11, 48, 19, 103, 85, 180, 466, 1, 263, 2, 188, 525, 1668, 1, 978, 26, 2429, 3927, 639]
16 [18, 25, 3928, 4, 3177, 81, 3929, 26, 3930, 5, 7, 169, 2998, 8, 3931, 642]
20 [109, 4, 34, 1655, 45, 1, 382, 4, 1592, 95, 40, 37, 19, 336, 329, 45, 51, 1, 488, 6]
16 [2, 1020, 572, 160, 7, 954, 304, 109

13 [1155, 230, 2669, 211, 573, 17, 1014, 24, 690, 12, 814, 1006, 2]
20 [1873, 1514, 1, 1314, 981, 106, 12, 1, 2, 699, 54, 1128, 1, 42, 59, 3959, 2655, 8, 62, 95]
22 [1, 2, 612, 31, 9, 21, 289, 3510, 2539, 3999, 72, 179, 7, 946, 2914, 70, 16, 1, 2181, 72, 478, 313]
19 [13, 59, 253, 2240, 821, 8, 9, 267, 1143, 451, 30, 483, 949, 2697, 109, 4, 20, 104, 2]
7 [42, 78, 15, 5, 395, 488, 2]
11 [85, 23, 80, 144, 1, 277, 6, 1, 2, 1609, 1239]
17 [81, 36, 3959, 12, 16, 141, 204, 482, 39, 149, 26, 8, 115, 68, 36, 4000, 2]
19 [647, 15, 140, 1, 66, 52, 473, 273, 4, 949, 145, 289, 336, 134, 45, 16, 389, 522, 2]
15 [196, 5, 19, 362, 6, 7, 259, 1, 2064, 4, 34, 1, 42, 879, 2]
20 [2052, 64, 30, 1, 1228, 97, 109, 1237, 786, 8, 284, 37, 604, 24, 2796, 1, 1030, 2, 2434, 1067]
14 [2489, 335, 153, 16, 30, 267, 28, 131, 4001, 12, 408, 1548, 570, 2]
10 [238, 1065, 39, 58, 14, 1, 2743, 6, 51, 2]
16 [220, 7, 146, 747, 224, 33, 72, 78, 15, 179, 7, 139, 79, 266, 15, 2]
8 [322, 47, 163, 396, 38, 99, 1890, 2]
24 [292,

15 [396, 38, 301, 24, 296, 105, 1, 238, 592, 6, 1, 2, 8, 9, 559]
19 [387, 4774, 17, 423, 38, 1, 2, 11, 4769, 1, 1667, 6, 3950, 434, 14, 11, 2585, 2326, 1364]
10 [15, 4, 190, 140, 555, 7, 417, 109, 121, 2]
7 [2798, 926, 327, 567, 2, 2406, 2799]
17 [289, 15, 547, 34, 377, 569, 33, 336, 656, 20, 5, 7, 185, 500, 19, 3878, 2]
10 [280, 555, 7, 346, 461, 410, 339, 2, 241, 301]
16 [23, 1558, 1012, 3423, 8, 1978, 385, 1283, 16, 147, 116, 19, 1083, 549, 2, 872]
23 [3901, 16, 26, 70, 56, 11, 64, 334, 13, 16, 21, 36, 7, 707, 1, 395, 66, 6, 46, 5, 78, 15, 2]
25 [9, 780, 28, 276, 260, 214, 4, 65, 460, 4, 34, 4773, 708, 619, 229, 1, 2, 163, 36, 260, 880, 821, 12, 7, 410]
17 [5, 13, 31, 70, 116, 1, 2, 462, 38, 99, 1418, 6, 52, 347, 4, 34, 7]
24 [9, 43, 80, 76, 120, 226, 1, 2, 39, 58, 210, 49, 507, 8, 7, 880, 82, 2244, 12, 959, 33, 496, 1474, 69]
21 [2754, 2572, 9, 403, 1085, 4, 160, 42, 35, 234, 278, 2670, 375, 206, 61, 148, 12, 1, 276, 2, 2537]
15 [2173, 2, 1610, 1, 308, 459, 39, 58, 21, 18, 288, 137

13 [27, 17, 597, 1, 2702, 1970, 6, 1, 26, 2, 3806, 901, 475]
15 [9, 641, 56, 78, 15, 82, 267, 34, 1238, 12, 1, 959, 1246, 2, 1520]
3 [2, 2051, 62]
16 [270, 653, 5, 1, 2336, 382, 3786, 4, 334, 15, 7, 730, 1558, 24, 4086, 2]
22 [11, 111, 63, 11, 2528, 7, 80, 139, 1347, 8, 11, 2873, 47, 1, 97, 410, 1, 72, 151, 535, 1, 2]
11 [2, 77, 35, 75, 92, 466, 1829, 12, 1488, 5, 271]
11 [32, 115, 315, 16, 444, 5, 895, 101, 530, 927, 2]
19 [3578, 85, 136, 120, 1, 2, 493, 1, 1870, 2044, 6, 1, 438, 228, 458, 21, 1, 327, 410]
17 [44, 1813, 7, 238, 448, 11, 68, 772, 257, 414, 594, 46, 1, 35, 2, 1053, 401]
13 [2, 2359, 3242, 8, 23, 17, 556, 2237, 1665, 979, 154, 576, 3241]
16 [300, 93, 619, 4, 71, 125, 220, 126, 6, 1338, 14, 71, 4322, 2151, 4323, 2]
11 [2, 15, 2073, 46, 57, 169, 1856, 96, 230, 1912, 252]
9 [6, 1166, 173, 1505, 63, 11, 89, 167, 2]
19 [6, 92, 270, 9, 541, 11, 661, 109, 4, 133, 1, 2, 9, 218, 1294, 2095, 12, 150, 376]
22 [50, 57, 17, 2681, 102, 2, 163, 105, 210, 1426, 832, 17, 16, 145, 46, 215

21 [9, 43, 111, 22, 120, 155, 33, 76, 39, 58, 2, 17, 904, 21, 7, 238, 4120, 568, 4121, 24, 2287]
6 [81, 776, 81, 7, 266, 2]
9 [982, 180, 4095, 1, 657, 995, 6, 2, 1067]
18 [2763, 300, 93, 83, 203, 14, 257, 1620, 38, 223, 450, 63, 11, 64, 203, 14, 31, 2]
21 [394, 1658, 3642, 82, 212, 78, 15, 16, 32, 59, 99, 2921, 6, 4110, 8, 37, 48, 210, 49, 334, 42]
15 [78, 15, 36, 483, 7, 1498, 549, 17, 54, 4, 75, 427, 45, 727, 2]
5 [2, 1850, 60, 459, 285]
16 [1350, 20, 2825, 780, 59, 53, 203, 218, 74, 8, 48, 32, 685, 14, 2, 3253]
9 [2, 9, 21, 612, 19, 66, 6, 95, 106]
18 [63, 9, 76, 6, 718, 9, 76, 6, 9, 43, 76, 3555, 665, 457, 72, 38, 20, 2]
17 [460, 5, 2114, 1913, 410, 4102, 102, 2114, 143, 4, 254, 166, 14, 386, 821, 410, 2]
27 [382, 34, 13, 17, 1, 628, 70, 123, 84, 4, 4099, 1, 25, 1, 276, 40, 133, 13, 448, 4062, 132, 49, 64, 133, 812, 95, 2]
16 [2605, 784, 51, 347, 4, 166, 22, 500, 2360, 336, 166, 2348, 2731, 23, 2, 475]
4 [188, 226, 644, 51]
15 [1, 2, 21, 1583, 46, 9, 64, 144, 5, 1956, 432, 717, 680

13 [46, 6, 1, 35, 37, 99, 2844, 1878, 14, 234, 278, 228, 2]
12 [2507, 797, 49, 45, 2195, 4, 1083, 1192, 3002, 2, 1814, 1228]
14 [254, 24, 1304, 134, 231, 38, 3766, 17, 7, 2, 738, 872, 3148, 1245]
5 [60, 266, 140, 479, 2]
18 [16, 26, 2, 21, 1, 174, 2230, 6, 53, 338, 13, 82, 34, 7, 594, 420, 14, 289]
18 [2292, 11, 525, 75, 1, 522, 16, 180, 5, 316, 1, 1325, 16, 223, 450, 4, 34, 33]
11 [780, 1002, 163, 2, 2624, 62, 18, 1388, 4, 4131, 3230]
18 [9, 122, 200, 2, 33, 655, 53, 2254, 6, 2679, 492, 169, 252, 93, 322, 155, 576, 154]
19 [112, 365, 5, 19, 199, 260, 674, 607, 42, 81, 16, 260, 208, 397, 37, 8, 1012, 2, 697]
13 [7, 2296, 1393, 108, 1202, 957, 715, 1506, 1394, 180, 2, 686, 1606]
17 [772, 4, 133, 16, 519, 148, 7, 2305, 29, 149, 26, 95, 35, 105, 1884, 1, 2]
15 [43, 200, 2, 8, 854, 151, 339, 9, 43, 656, 54, 9, 148, 4, 1530]
10 [23, 55, 7, 447, 9, 43, 462, 62, 74, 2]
9 [1, 3656, 14, 1, 2, 21, 1, 174, 108]
16 [1, 2513, 14, 132, 4042, 662, 12, 39, 149, 2, 931, 4, 286, 14, 71, 1619]
16 [9, 138

4 [50, 57, 1912, 2]
22 [3473, 2, 1020, 715, 39, 58, 12, 1549, 6, 2698, 2699, 1020, 8, 102, 1208, 4081, 462, 193, 215, 22, 16, 1677]
7 [20, 1424, 6, 1, 3912, 1912, 2]
14 [9, 2372, 141, 1265, 39, 104, 72, 34, 65, 11, 451, 5, 295, 2]
14 [210, 1798, 763, 6, 1556, 8, 30, 179, 1020, 715, 69, 6, 13, 2]
22 [42, 26, 39, 58, 21, 719, 68, 1021, 1799, 4, 133, 135, 282, 134, 27, 237, 55, 30, 75, 4, 432, 2]
5 [7, 26, 568, 2635, 2]
19 [51, 1679, 1141, 6, 1, 175, 109, 29, 1, 2, 574, 446, 14, 79, 245, 722, 19, 1, 563]
22 [2444, 380, 68, 7, 468, 8, 9, 267, 418, 1, 2, 206, 9, 84, 4, 34, 99, 2185, 850, 8, 111, 35]
19 [455, 1, 2, 1951, 551, 3338, 106, 40, 186, 2810, 1016, 6, 444, 44, 24, 51, 102, 633, 85]
24 [41, 343, 233, 30, 94, 1205, 46, 160, 404, 6, 1, 486, 24, 1, 1088, 346, 25, 220, 19, 412, 1, 42, 407, 2]
11 [35, 538, 453, 335, 296, 1576, 7, 718, 721, 2049, 2]
12 [656, 63, 457, 1581, 1, 397, 52, 1997, 6, 229, 1, 2]
19 [2999, 835, 14, 15, 4, 274, 400, 974, 4, 114, 35, 5, 38, 2853, 812, 793, 835, 14, 2

16 [439, 41, 78, 15, 5, 1058, 27, 269, 4, 1, 464, 213, 3, 1059, 962, 1060]
21 [19, 7, 77, 33, 343, 1695, 71, 466, 39, 58, 778, 1, 174, 126, 17, 145, 14, 1, 3, 3835, 512]
17 [10, 50, 57, 153, 31, 6, 164, 162, 11, 130, 13, 33, 11, 43, 143, 2, 3]
18 [10, 121, 30, 393, 16, 279, 315, 32, 64, 526, 112, 438, 228, 4, 378, 437, 2, 3]
18 [10, 121, 30, 393, 16, 279, 315, 32, 64, 526, 112, 438, 228, 4, 378, 437, 2, 3]
13 [157, 20, 5, 83, 9, 43, 200, 18, 25, 454, 46, 1730, 3]
18 [10, 121, 30, 393, 16, 279, 315, 32, 64, 526, 112, 438, 228, 4, 378, 437, 2, 3]
17 [10, 30, 1, 131, 49, 177, 1, 97, 79, 6, 191, 184, 19, 18, 25, 2, 3]
20 [36, 1322, 18, 4, 185, 35, 41, 336, 46, 166, 22, 88, 14, 7, 764, 1187, 1093, 519, 3, 265]
13 [10, 41, 44, 298, 14, 291, 302, 30, 255, 16, 47, 2, 3]
21 [159, 245, 428, 261, 235, 42, 515, 14, 52, 64, 293, 364, 388, 24, 587, 1, 132, 545, 17, 600, 546]
11 [324, 127, 689, 246, 1, 185, 207, 134, 197, 3, 723]
13 [10, 41, 44, 298, 14, 291, 302, 30, 255, 16, 47, 2, 3]
4 [51, 1, 3, 

17 [10, 30, 1, 131, 49, 177, 1, 97, 79, 6, 191, 184, 19, 18, 25, 2, 3]
21 [82, 494, 41, 514, 6, 196, 4, 144, 1736, 9, 130, 1, 1882, 6, 15, 442, 831, 16, 68, 1515, 3]
17 [10, 30, 1, 131, 49, 177, 1, 97, 79, 6, 191, 184, 19, 18, 25, 2, 3]
10 [3, 363, 323, 138, 193, 595, 66, 139, 126, 3269]
19 [204, 5, 485, 4151, 115, 1627, 1312, 44, 65, 30, 80, 337, 7, 436, 48, 617, 708, 22, 3]
18 [1323, 2102, 1918, 11, 1641, 13, 32, 501, 934, 4, 975, 141, 4, 691, 47, 15, 3, 3281]
20 [4, 329, 960, 1460, 1049, 277, 1254, 2377, 1510, 17, 15, 15, 1374, 13, 1313, 960, 2378, 2, 3, 1880]
19 [4, 329, 960, 1460, 1049, 277, 1254, 2377, 1510, 17, 15, 15, 1374, 13, 1313, 960, 2378, 2, 3]
19 [1928, 1097, 174, 481, 12, 1, 3, 12, 60, 356, 1271, 284, 252, 24, 168, 96, 24, 300, 93]
21 [82, 494, 41, 514, 6, 196, 4, 144, 1736, 9, 130, 1, 1882, 6, 15, 442, 831, 16, 68, 1515, 3]
16 [1107, 50, 685, 62, 458, 6, 218, 453, 8, 783, 808, 826, 810, 1008, 1062, 3]
19 [41, 514, 6, 196, 4, 144, 1736, 9, 130, 1, 1882, 6, 15, 442, 831,

18 [4204, 4205, 180, 54, 208, 708, 64, 34, 1842, 246, 66, 825, 400, 390, 328, 7, 885, 4206]
18 [159, 96, 96, 96, 1525, 224, 144, 1, 536, 560, 8, 295, 1319, 4, 16, 424, 1629, 205]
17 [10, 50, 57, 153, 31, 6, 164, 162, 11, 130, 13, 33, 11, 43, 143, 2, 3]
6 [516, 15, 59, 517, 351, 3]
9 [62, 492, 1, 132, 1239, 126, 5, 127, 3]
19 [768, 2780, 580, 1, 581, 18, 108, 117, 172, 47, 24, 637, 61, 224, 50, 57, 3, 2130, 3291]
19 [157, 9, 951, 237, 12, 534, 14, 755, 394, 467, 50, 303, 57, 8, 9, 945, 60, 67, 3]
18 [10, 13, 5, 100, 181, 16, 18, 25, 5, 19, 195, 7, 113, 24, 128, 26, 2, 3]
18 [4207, 3, 51, 4141, 47, 45, 597, 486, 154, 630, 4206, 631, 11, 1709, 4, 34, 576, 265]
14 [41, 398, 8, 7, 426, 6, 49, 559, 94, 28, 561, 51, 3, 23]
19 [1928, 1097, 174, 481, 12, 1, 3, 12, 60, 356, 1271, 284, 252, 24, 168, 96, 24, 300, 93]
12 [159, 375, 42, 442, 76, 88, 652, 4, 185, 35, 1106, 3]
18 [10, 13, 5, 100, 181, 16, 18, 25, 5, 19, 195, 7, 113, 24, 128, 26, 2, 3]
18 [9, 64, 1127, 601, 2781, 119, 20, 271, 33, 9, 4

9 [241, 5, 27, 4112, 988, 32, 936, 38, 3]
18 [10, 13, 5, 100, 181, 16, 18, 25, 5, 19, 195, 7, 113, 24, 128, 26, 2, 3]
18 [20, 5, 211, 338, 90, 49, 37, 446, 14, 1, 132, 1676, 700, 12, 1, 344, 3, 2380]
11 [140, 1227, 105, 441, 300, 64, 9, 334, 11, 300, 3]
21 [9, 138, 540, 33, 76, 331, 96, 59, 253, 1729, 71, 3996, 351, 64, 179, 7, 276, 14, 71, 1395, 3]
20 [224, 20, 434, 1, 77, 583, 81, 41, 11, 76, 11, 64, 3218, 7, 288, 578, 244, 484, 2, 642]
6 [93, 5, 131, 763, 1436, 3]
23 [230, 190, 68, 7, 852, 503, 6, 77, 68, 1, 103, 66, 574, 500, 2363, 105, 47, 62, 1, 3517, 20, 2177, 3]
19 [4221, 1, 104, 22, 1, 1648, 1475, 931, 4, 3211, 1497, 1, 103, 310, 224, 17, 145, 3, 4222]
23 [1061, 66, 6, 53, 498, 282, 22, 1, 3, 5, 54, 208, 6, 90, 35, 326, 361, 12, 374, 183, 509, 1010, 24]
12 [10, 93, 8, 57, 37, 7, 1375, 4, 20, 217, 2, 3]
21 [41, 1386, 4, 93, 88, 59, 1247, 254, 45, 139, 35, 33, 59, 19, 1247, 1, 323, 45, 66, 1153, 3]
18 [159, 96, 96, 96, 1525, 224, 144, 1, 536, 560, 8, 295, 1319, 4, 16, 424, 1629,

9 [159, 64, 257, 733, 20, 4, 3, 333, 1105]
13 [2393, 68, 36, 835, 14, 95, 46, 4, 1601, 1899, 219, 114, 3]
12 [16, 389, 522, 1918, 190, 3, 2, 384, 566, 147, 4, 3212]
16 [452, 1, 349, 6, 1, 192, 5, 4, 259, 49, 8, 247, 490, 118, 3, 321]
16 [10, 86, 15, 7, 345, 104, 182, 29, 359, 125, 63, 15, 354, 13, 2, 3]
17 [41, 115, 1, 18, 277, 37, 189, 4, 255, 88, 246, 1, 97, 26, 2122, 150, 3]
16 [452, 1, 349, 6, 1, 192, 5, 4, 259, 49, 8, 247, 490, 118, 3, 321]
16 [10, 18, 25, 5, 165, 124, 4, 170, 1, 178, 6, 1, 77, 156, 2, 3]
16 [4225, 4226, 580, 581, 18, 108, 117, 172, 4227, 61, 224, 50, 57, 3, 688, 1934]
19 [10, 5, 13, 36, 31, 70, 116, 120, 155, 84, 4, 202, 73, 98, 12, 1, 125, 2, 3]
16 [97, 109, 30, 75, 4, 1468, 1, 42, 207, 11, 111, 41, 81, 485, 1366, 3]
20 [2789, 601, 1301, 14, 421, 748, 1223, 598, 8, 88, 8, 268, 9, 1095, 243, 1, 379, 68, 139, 3]
6 [3, 40, 264, 312, 127, 274]
3 [20, 358, 3]
16 [509, 802, 7, 104, 14, 87, 570, 1003, 993, 3687, 152, 457, 272, 408, 3192, 3]
14 [9, 867, 694, 3154, 1820,

20 [509, 20, 26, 9, 111, 352, 67, 8, 778, 485, 22, 90, 35, 115, 101, 9, 85, 20, 506, 3]
4 [286, 5, 69, 3]
19 [4236, 9, 38, 301, 7, 426, 260, 33, 754, 32, 186, 67, 793, 109, 4, 2149, 71, 1459, 3]
17 [20, 5, 18, 25, 30, 846, 436, 221, 16, 40, 264, 38, 1879, 70, 310, 49, 3]
13 [366, 5, 1, 6, 46, 6, 150, 225, 4, 112, 379, 1697, 3]
19 [10, 15, 59, 148, 13, 123, 496, 72, 166, 22, 273, 19, 794, 34, 473, 13, 47, 2, 3]
19 [10, 83, 110, 73, 98, 86, 1, 114, 256, 22, 61, 250, 8, 135, 61, 147, 201, 27, 2]
19 [10, 5, 13, 36, 31, 70, 116, 120, 155, 84, 4, 202, 73, 98, 12, 1, 125, 2, 3]
19 [10, 15, 59, 148, 13, 123, 496, 72, 166, 22, 273, 19, 794, 34, 473, 13, 47, 2, 3]
17 [3, 91, 557, 4234, 38, 759, 648, 2760, 591, 3251, 40, 2362, 2080, 105, 4235, 2567, 249]
7 [333, 5, 7, 1207, 596, 906, 3]
4 [68, 1, 224, 3]
19 [10, 5, 13, 36, 31, 70, 116, 120, 155, 84, 4, 202, 73, 98, 12, 1, 125, 2, 3]
19 [20, 26, 9, 111, 352, 67, 8, 778, 485, 22, 90, 35, 115, 101, 9, 85, 20, 506, 3]
18 [9, 38, 301, 7, 426, 260, 33,

8 [1056, 42, 1205, 1408, 19, 310, 848, 3]
20 [10, 1, 35, 43, 28, 4, 152, 23, 18, 5, 161, 13, 14, 95, 62, 227, 74, 27, 175, 2]
17 [10, 127, 8, 23, 89, 4, 160, 293, 6, 20, 26, 40, 64, 65, 13, 2, 3]
19 [10, 83, 110, 73, 98, 86, 1, 114, 256, 22, 61, 250, 8, 135, 61, 147, 201, 27, 2]
19 [10, 83, 110, 73, 98, 86, 1, 114, 256, 22, 61, 250, 8, 135, 61, 147, 201, 27, 2]
21 [352, 38, 7, 494, 6, 173, 593, 48, 40, 451, 22, 7, 2303, 1110, 8, 167, 1027, 14, 16, 1110, 3]
20 [10, 1, 35, 43, 28, 4, 152, 23, 18, 5, 161, 13, 14, 95, 62, 227, 74, 27, 175, 2]
19 [10, 83, 110, 73, 98, 86, 1, 114, 256, 22, 61, 250, 8, 135, 61, 147, 201, 27, 2]
19 [10, 83, 110, 73, 98, 86, 1, 114, 256, 22, 61, 250, 8, 135, 61, 147, 201, 27, 2]
21 [10, 18, 25, 264, 348, 52, 1, 77, 340, 5, 123, 115, 9, 236, 23, 103, 59, 7, 440, 353, 320]
15 [10, 11, 72, 151, 111, 23, 5, 1, 465, 27, 119, 20, 26, 2, 3]
21 [159, 245, 428, 261, 235, 42, 515, 14, 52, 64, 293, 364, 388, 24, 587, 1, 132, 545, 17, 600, 546]
21 [159, 245, 428, 261, 235,

5 [14, 92, 377, 908, 3]
16 [10, 18, 25, 5, 165, 124, 4, 170, 1, 178, 6, 1, 77, 156, 2, 3]
16 [10, 18, 25, 5, 165, 124, 4, 170, 1, 178, 6, 1, 77, 156, 2, 3]
6 [4252, 513, 14, 1, 258, 3]
16 [10, 18, 25, 5, 165, 124, 4, 170, 1, 178, 6, 1, 77, 156, 2, 3]
16 [10, 18, 25, 5, 165, 124, 4, 170, 1, 178, 6, 1, 77, 156, 2, 3]
17 [1057, 786, 252, 1103, 17, 801, 37, 215, 101, 132, 499, 199, 297, 12, 20, 26, 3]
10 [9, 130, 1, 1, 391, 4068, 1, 457, 2266, 3]
5 [335, 380, 9, 559, 3]
10 [9, 1839, 66, 6, 11, 368, 4, 408, 2951, 3]
16 [10, 18, 25, 5, 165, 124, 4, 170, 1, 178, 6, 1, 77, 156, 2, 3]
16 [10, 18, 25, 5, 165, 124, 4, 170, 1, 178, 6, 1, 77, 156, 2, 3]
22 [159, 64, 257, 212, 31, 83, 168, 96, 5, 1285, 1234, 14, 49, 52, 82, 1127, 312, 74, 274, 560, 214, 3]
13 [10, 20, 3, 5, 41, 865, 357, 15, 8, 1030, 81, 19, 582]
19 [157, 305, 169, 43, 65, 747, 45, 408, 36, 1, 1942, 624, 878, 276, 4, 134, 1407, 169, 3]
17 [10, 50, 57, 153, 31, 6, 164, 162, 11, 130, 13, 33, 11, 43, 143, 2, 3]
16 [10, 18, 25, 5, 165, 

17 [10, 50, 57, 153, 31, 6, 164, 162, 11, 130, 13, 33, 11, 43, 143, 2, 3]
14 [9, 287, 151, 360, 14, 79, 53, 967, 21, 7, 110, 45, 442, 3]
25 [10, 9, 76, 87, 8, 15, 89, 4, 239, 231, 8, 240, 20, 172, 47, 129, 8, 75, 209, 6, 57, 8, 93, 2, 171]
17 [10, 50, 57, 153, 31, 6, 164, 162, 11, 130, 13, 33, 11, 43, 143, 2, 3]
17 [10, 50, 57, 153, 31, 6, 164, 162, 11, 130, 13, 33, 11, 43, 143, 2, 3]
10 [963, 292, 173, 17, 145, 593, 66, 294, 328, 3]
17 [20, 6, 168, 96, 5, 36, 66, 246, 83, 110, 471, 8, 36, 54, 1648, 4407, 521]
14 [56, 415, 72, 384, 1, 24, 1019, 435, 269, 48, 40, 661, 69, 3]
18 [68, 1, 103, 358, 17, 20, 145, 52, 5, 1448, 2087, 8, 81, 19, 7, 346, 2087, 3]
12 [83, 85, 9, 1565, 469, 27, 90, 49, 249, 53, 2145, 3]
17 [10, 50, 57, 153, 31, 6, 164, 162, 11, 130, 13, 33, 11, 43, 143, 2, 3]
6 [2036, 17, 27, 1, 3, 4]
6 [516, 15, 59, 517, 351, 3]
10 [245, 380, 373, 17, 261, 579, 871, 1096, 4428, 3]
14 [10, 18, 5, 262, 251, 1, 35, 50, 176, 1, 242, 91, 3, 3]
6 [448, 11, 1147, 805, 196, 3]
21 [10, 18

22 [4215, 56, 343, 1746, 4216, 47, 1, 1517, 203, 62, 1, 535, 6, 20, 26, 32, 2332, 4, 1235, 69, 3, 1758]
21 [159, 463, 212, 11, 1, 66, 139, 271, 22, 3, 35, 37, 1626, 198, 709, 4, 1518, 219, 114, 12, 727]
16 [400, 621, 1569, 1, 2, 21, 19, 2891, 1, 16, 287, 103, 478, 27, 3150, 335]
7 [42, 1205, 1408, 19, 310, 848, 3]
12 [20, 5, 83, 9, 43, 200, 18, 25, 454, 46, 1730, 3]
23 [296, 501, 69, 6, 1, 38, 7, 398, 340, 9, 182, 330, 4, 1144, 67, 22, 71, 1946, 14, 7, 215, 142, 2]
14 [174, 548, 6, 2, 21, 273, 568, 3097, 5, 1966, 21, 16, 654, 1385]
21 [49, 52, 144, 40, 37, 621, 37, 1906, 2750, 40, 111, 16, 7, 2651, 5, 7, 558, 6, 49, 123, 3]
18 [10, 83, 94, 23, 842, 187, 4, 1, 42, 63, 1, 787, 1004, 69, 4, 194, 2, 3]
19 [10, 15, 59, 148, 13, 123, 496, 72, 166, 22, 273, 19, 794, 34, 473, 13, 47, 2, 3]
23 [41, 1013, 1764, 64, 781, 14, 11, 118, 33, 11, 138, 2103, 1, 797, 4, 179, 95, 2786, 55, 757, 1604, 80, 3]
19 [10, 5, 13, 36, 31, 70, 116, 120, 155, 84, 4, 202, 73, 98, 12, 1, 125, 2, 3]
14 [10, 18, 5, 262

In [10]:
maxx = 0
c=0
for ll in X:
    c=len(ll)
    if c>maxx:
        maxx=c
print('Max',maxx)
X = pad_sequences(X)
print(len(X[0]))
print (X)

Max 29
29
[[   0    0    0 ... 1324 1409  743]
 [   0    0    0 ...  233  724   17]
 [   0    0    0 ...  207  371  670]
 ...
 [   0    0    0 ...   72   65    3]
 [   0    0    0 ... 1022 1423   74]
 [   0    0    0 ...  197    3  723]]


In [11]:
embed_dim = 128
lstm_out = 128
model = Sequential()#call the sequential model
model.add(Embedding(batch_size, embed_dim,input_length = X.shape[1], dropout=0.2))

model.add(LSTM(lstm_out, dropout_U=0.2, dropout_W=0.2))
model.add(Dense(2,activation='softmax'))#
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

c:\users\mahalakshumi\myenv\lib\site-packages\ipykernel_launcher.py:4: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  after removing the cwd from sys.path.
c:\users\mahalakshumi\myenv\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(128, dropout=0.2, recurrent_dropout=0.2)`
  


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 29, 128)           640000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 258       
Total params: 771,842
Trainable params: 771,842
Non-trainable params: 0
_________________________________________________________________
None


In [12]:

print(data['sentiment'].values)
Y = pd.get_dummies(data['sentiment']).values
print(Y)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.33, random_state = 42)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

['Positive' 'Positive' 'Positive' ... 'Positive' 'Negative' 'Positive']
[[0 1]
 [0 1]
 [0 1]
 ...
 [0 1]
 [1 0]
 [0 1]]
(7188, 29) (7188, 2)
(3541, 29) (3541, 2)


In [25]:
model.fit(X_train, Y_train, nb_epoch = 3, batch_size=32, verbose = 2)

c:\users\mahalakshumi\myenv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/3
 - 11s - loss: 0.1219 - acc: 0.9516
Epoch 2/3
 - 11s - loss: 0.1050 - acc: 0.9598
Epoch 3/3
 - 11s - loss: 0.0885 - acc: 0.9642


In [40]:
from tweepy import Stream
from tweepy import OAuthHandler
from tweepy.streaming import StreamListener
import json

In [41]:
ckey=" "
csecret=" "
atoken=" "
asecret=" "

In [42]:
class listener(StreamListener):

    def on_data(self, data):
        all_data = json.loads(data)
        
        tweet = all_data["text"]
        s2 = tweet
        hh = tokenizer.texts_to_sequences([s2])
        X_test[9].shape
        hh = pad_sequences(hh, maxlen=29)
        hh=np.array(hh[0]).reshape(1,29)
        x=model.predict(hh)
        print(x)
        if(x[0][0]>x[0][1]):
            sentiment_value='negative'
        else:
            sentiment_value='positive'
        fp=open("sentiment_text.txt","a")
        fp.write(sentiment_value)
        fp.write('\n')
        fp.close()
        print((tweet,sentiment_value))
        
        return True

    def on_error(self, status):
        print (status)

In [ ]:
fp=open("sentiment_text.txt","w")
fp.close()
liveword=input("Enter the topic:")

In [66]:
auth = OAuthHandler(ckey, csecret)
auth.set_access_token(atoken, asecret)

twitterStream = Stream(auth, listener())
twitterStream.filter(track=[liveword])

[[0.81032723 0.18967274]]
('@madhukishwar @narendramodi Modi chose a yardstick to measure Nehru and erstwhile Cong Govt. and it showed them lac… https://t.co/2pXrlqufet', 'negative')
[[0.00479791 0.99520206]]
('RT @ashoswai: Raghuram Rajan was had a Ph.D. in Managment from MIT, Urjit Patel  MPhil in Economics from Oxford &amp; Ph.D. in Economics from Y…', 'positive')
[[0.40618786 0.5938122 ]]
('RT @nselrevenge: @NSELfight @ramgopaldass_77 @RavinarIN @narendramodi @imVkohli @shweta_shalini @SushmaSwaraj @rammadhavbjp @sanjeevsanyal…', 'positive')
[[0.40618786 0.5938122 ]]
('RT @ThunderIndia93: @sunilkpal @muralydoctrack1 @SunitaG1962 @RaiBahadur13 @Ashwita88 @romy1965 @kamleshtewari90 @balooni_satish @jyotsnava…', 'positive')
[[0.56599647 0.43400356]]
('RT @Gadhvilaxman: BC Arshad warsi ke fan bhi aa jao Modi aur BJP ko harane ka credit lelo aage nahi milne wala 😂😭 https://t.co/TboJossKqt', 'negative')
[[0.7013741  0.29862592]]
('RT @RoflGandhi_: Sangh ki head side ki kuttai ho gayi toh

[[0.9986078  0.00139225]]
('RT @_Abhinav96: One-way communication like “Mann ki Baat” where Modi plays Sant Baparam cannot be the only method of communication...😂😂\n\nMe…', 'negative')
[[0.8386374  0.16136262]]
('RT @AtomicBlow: Modi carved another neech for himself.\n#CongressWinsBig\nhttps://t.co/WklcBmDhyk', 'negative')
[[9.999964e-01 3.571101e-06]]
('RT @RavinarIN: Ten Messages For Modi... HORRIFYING to find "Justice 4 all, Appeasement of none" has turned into blazing Muslim-appeasement.…', 'negative')
[[9.9966693e-01 3.3310283e-04]]
('RT @BJP4India: It is only partnerships, that will get us to our goals - partnerships between citizens, partnerships between communities and…', 'negative')
[[0.99429375 0.00570617]]
('Market Bhakths! Adhia, Shaktikanta Das, Arun Jaitley, Urjit Patel &amp; everyone who works against their profit is wron… https://t.co/GHXunlSRfP', 'negative')
[[0.9864113  0.01358872]]
('RT @redLotus1_: Hunar haath, padho Pardes, nayi manzil, guraan-labdob, nayi roshni, 

KeyboardInterrupt: 